/**
 * The measured tokens as a tailwind config, for a port landing somewhere that
 * is already that kind of place.
 *
 * Everything goes under theme.extend rather than theme, on purpose: replacing
 * the whole theme would delete tailwind's own scale, and the point of this
 * file is to add the legacy app's real values beside it, not to amputate the
 * framework somebody chose.
 *
 *   tailwind: true
 */
const px = (v) => `${v}px`;

export function buildConfig(tokens, source) {
  const sizes = Object.fromEntries(Object.entries(tokens.size ?? {}).map(([k, v]) => [k, px(v)]));
  const spacing = Object.fromEntries((tokens.space ?? []).map((v, i) => [`p${i}`, px(v)]));
  const radius = Object.fromEntries(Object.entries(tokens.radius ?? {}).map(([k, v]) => [k, typeof v === "number" ? px(v) : v]));
  const shadows = tokens.elevation
    ? Object.fromEntries(Object.entries(tokens.elevation).map(([k, v]) => [k, v]))
    : tokens.shadow ? { card: tokens.shadow } : {};

  return `/**
 * Generated by portamp from ${source}. Everything sits under extend so
 * tailwind's own scale survives; these are the legacy app's measured values,
 * added beside it.
 */
export default {
  theme: {
    extend: {
      colors: ${JSON.stringify(tokens.color ?? {}, null, 6).replace(/\n}/, "\n      }")},
      fontSize: ${JSON.stringify(sizes, null, 6).replace(/\n}/, "\n      }")},
      spacing: ${JSON.stringify(spacing, null, 6).replace(/\n}/, "\n      }")},
      borderRadius: ${JSON.stringify(radius, null, 6).replace(/\n}/, "\n      }")},
      boxShadow: ${JSON.stringify(shadows, null, 6).replace(/\n}/, "\n      }")},
    },
  },
};
`;
}

export default {
  name: "output-tailwind",
  version: "0.1.0",
  class: "output",
  setup({ on, log }) {
    on("emit", async (ctx) => {
      if (!ctx.config.tailwind) return log.debug("not requested");
      if (!ctx.tokens) return log.info("no tokens to write");

      const { provenance, ...tokens } = ctx.tokens;
      await ctx.write("tailwind.config.js", buildConfig(tokens, "the measured legacy design"));
      if (ctx.uplift?.tokens) {
        await ctx.write("tailwind.modern.config.js", buildConfig(ctx.uplift.tokens, "the proposed uplift; see DESIGN_UPLIFT.md before adopting it"));
      }
      log.info(`tailwind config written${ctx.uplift ? ", measured and proposed" : ""}`);
    });
  },
};
