import { buildSpec, renderSpec } from "./spec.js";

/**
 * Emits the conformance suite. Runs whenever there is an exploration to write
 * one from, because a port with no way to check it against the original is the
 * thing this tool exists to stop shipping.
 */
export default {
  name: "output-tests",
  version: "0.1.0",
  class: "output",
  setup({ on, log }) {
    on("emit", async (ctx) => {
      // The states suite needs no exploration and no server: it reads the
      // emitted components back and fails if any lost a state. It asserts
      // presence in the source, which is exactly the claim it makes.
      if (ctx.screens.length) {
        await ctx.write("tests/states.test.js", STATES_SUITE);
        log.info("states suite written; it reads the emitted components back");
      }

      const exploration = ctx.sources.exploration;
      if (!exploration || !ctx.model) return log.debug("nothing was explored, so there is nothing to assert");

      const spec = buildSpec(ctx.model, exploration, { portUrl: ctx.config.portUrl });
      await ctx.write("tests/conformance.spec.js", renderSpec(spec));

      log.info(`${spec.cases.length} conformance test(s) written from what the original did`);
      const performed = exploration.budget?.performed ?? 0;
      const budget = exploration.budget?.maxSteps ?? performed;
      if (performed >= budget) {
        ctx.unverified(
          `The exploration used its whole budget of ${budget} steps, so the conformance suite covers what it reached and no more. ` +
            "Raise explore.maxSteps for a wider suite."
        );
      }
    });
  },
};

const STATES_SUITE = `import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";

/**
 * Generated by portamp. Every ported component ships with loading, error,
 * empty and body states, because an empty state that renders nothing is the
 * most common port defect. This suite reads the components back and fails
 * the moment somebody deletes one of those states. It checks the source, not
 * the render; the storybook stories carry the rendered half of the claim.
 */
const root = join(process.cwd(), "src", "features");
const components = existsSync(root)
  ? readdirSync(root, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .flatMap((entry) => readdirSync(join(root, entry.name))
        .filter((file) => /\\.(jsx|vue|svelte)$/.test(file) && !/\\.stories\\./.test(file))
        .map((file) => join(root, entry.name, file)))
  : [];

test("every ported component still carries its four states", () => {
  assert.ok(components.length, "no components found under src/features — run this from the port's root");
  for (const file of components) {
    const source = readFileSync(file, "utf8");
    for (const state of ["loading", "error"]) {
      assert.ok(new RegExp("\\\\b" + state + "\\\\b").test(source), file + " no longer mentions its " + state + " state");
    }
    assert.ok(/Nothing to show|empty|length === 0|\\.length\\b/.test(source), file + " no longer handles the empty state");
  }
});
`;
