import { buildSpec, renderSpec } from "./spec.js";
import { jsString } from "../dsp-ir/emit.js";

/**
 * A recording replayed is drift measured. Each step the exploration took —
 * what was clicked or typed, and what screen it landed on — becomes one
 * replayable step; the emitted spec walks them against the served port and
 * reports drift per step instead of one flat failure. Only steps whose
 * action names a selector replay; the rest are counted so the gap has a
 * size.
 */
export function replaySteps(exploration) {
  const steps = [];
  let skipped = 0;
  for (const step of exploration?.steps ?? []) {
    const action = step.action ?? {};
    if (!action.selector || !/^(click|fill|select)$/.test(action.kind ?? "")) {
      skipped += 1;
      continue;
    }
    steps.push({
      kind: action.kind,
      selector: action.selector,
      label: action.label ?? null,
      value: action.kind === "fill" ? "" : action.value ?? null,
    });
  }
  return { steps, skipped };
}

/**
 * Emits the conformance suite. Runs whenever there is an exploration to write
 * one from, because a port with no way to check it against the original is the
 * thing this tool exists to stop shipping.
 */
export default {
  name: "output-tests",
  version: "0.1.0",
  class: "output",
  setup({ on, log }) {
    on("emit", async (ctx) => {
      // The states suite needs no exploration and no server: it reads the
      // emitted components back and fails if any lost a state. It asserts
      // presence in the source, which is exactly the claim it makes.
      if (ctx.screens.length) {
        await ctx.write("tests/states.test.js", STATES_SUITE);
        log.info("states suite written; it reads the emitted components back");
      }

      const exploration = ctx.sources.exploration;
      if (!exploration || !ctx.model) return log.debug("nothing was explored, so there is nothing to assert");

      const spec = buildSpec(ctx.model, exploration, { portUrl: ctx.config.portUrl });
      await ctx.write("tests/conformance.spec.js", renderSpec(spec));

      // The recording, replayed: every step with a selector becomes one
      // replay step, and the spec reports drift per step rather than one
      // flat failure. Recorded input values are not reproduced; a fill
      // replays as an empty string on purpose.
      const replay = replaySteps(exploration);
      if (replay.steps.length) {
        await ctx.write("tests/replay.spec.js", REPLAY_SPEC(replay, ctx.config.portUrl ?? null));
        log.info(`${replay.steps.length} recorded step(s) replayable, ${replay.skipped} without a selector`);
        if (replay.skipped) {
          ctx.unverified(`${replay.skipped} recorded step(s) carry no selector and cannot replay; the drift report covers the ${replay.steps.length} that can.`);
        }
      }

      log.info(`${spec.cases.length} conformance test(s) written from what the original did`);
      const performed = exploration.budget?.performed ?? 0;
      const budget = exploration.budget?.maxSteps ?? performed;
      if (performed >= budget) {
        ctx.unverified(
          `The exploration used its whole budget of ${budget} steps, so the conformance suite covers what it reached and no more. ` +
            "Raise explore.maxSteps for a wider suite."
        );
      }
    });
  },
};

const STATES_SUITE = `import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";

/**
 * Generated by portamp. Every ported component ships with loading, error,
 * empty and body states, because an empty state that renders nothing is the
 * most common port defect. This suite reads the components back and fails
 * the moment somebody deletes one of those states. It checks the source, not
 * the render; the storybook stories carry the rendered half of the claim.
 */
const root = join(process.cwd(), "src", "features");
const components = existsSync(root)
  ? readdirSync(root, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .flatMap((entry) => readdirSync(join(root, entry.name))
        .filter((file) => /\\.(jsx|vue|svelte)$/.test(file) && !/\\.stories\\./.test(file))
        .map((file) => join(root, entry.name, file)))
  : [];

test("every ported component still carries its four states", () => {
  assert.ok(components.length, "no components found under src/features — run this from the port's root");
  for (const file of components) {
    const source = readFileSync(file, "utf8");
    for (const state of ["loading", "error"]) {
      assert.ok(new RegExp("\\\\b" + state + "\\\\b").test(source), file + " no longer mentions its " + state + " state");
    }
    assert.ok(/Nothing to show|empty|length === 0|\\.length\\b/.test(source), file + " no longer handles the empty state");
  }
});
`;

const REPLAY_SPEC = (replay, portUrl) => `/**
 * Generated by portamp. The recording, replayed against the port: each step
 * below is something a person actually did in the legacy app, and the suite
 * reports drift per step instead of stopping at the first difference.
 * Recorded input values are not reproduced; a fill replays empty on purpose.
 * Needs @playwright/test and a served port; without either it skips and
 * says so.
 */
import { test, expect } from "@playwright/test";

const PORT_URL = process.env.PORT_URL ?? ${portUrl ? jsString(portUrl) : "null"};

const STEPS = ${JSON.stringify(replay.steps, null, 2)};

test("the recording replays with drift reported per step", async ({ page }) => {
  test.skip(!PORT_URL, "set PORT_URL to the served port to replay the recording");
  const drift = [];
  await page.goto(PORT_URL);
  for (const [i, step] of STEPS.entries()) {
    const target = page.locator(step.selector).first();
    if ((await target.count()) === 0) {
      drift.push(\`step \${i + 1}: \${step.selector} is not on the page (the recording \${step.kind}ed it\${step.label ? \`, labelled \${JSON.stringify(step.label)}\` : ""})\`);
      continue;
    }
    try {
      if (step.kind === "click") await target.click({ timeout: 3000 });
      else if (step.kind === "fill") await target.fill(step.value ?? "", { timeout: 3000 });
      else if (step.kind === "select") await target.selectOption(step.value ?? "", { timeout: 3000 });
    } catch (err) {
      drift.push(\`step \${i + 1}: \${step.kind} on \${step.selector} failed: \${err.message.split("\\n")[0]}\`);
    }
  }
  expect(drift, \`\${drift.length} of \${STEPS.length} step(s) drifted:\\n\${drift.join("\\n")}\`).toEqual([]);
});
`;
