/**
 * A smoke script for the API the legacy app depends on. Written, never run:
 * portamp does not make live calls without the policy gate, and this file is
 * a person's to execute against a server they are authorized to hit. GETs
 * only, because a smoke test that writes is a load test with a pen.
 */

const templated = (path) =>
  String(path)
    .replace(/\$\{([^}]+)\}/g, (_, name) => `\${${name.split(".").pop().trim().toUpperCase()}:?set ${name.split(".").pop().trim().toUpperCase()}}`)
    .split("?")[0];

export function buildScript(calls) {
  const gets = [];
  const seen = new Set();
  let skipped = 0;
  for (const call of calls) {
    if (call.method !== "GET") { skipped += 1; continue; }
    const path = templated(call.path);
    if (seen.has(path)) continue;
    seen.add(path);
    gets.push(path);
  }
  return { gets, skipped };
}

export default {
  name: "output-curl",
  version: "0.1.0",
  class: "output",
  setup({ on, log }) {
    on("emit", async (ctx) => {
      if (!ctx.config.curl) return log.debug("not requested");
      const { gets, skipped } = buildScript(ctx.api.calls);
      if (!gets.length) return log.debug("no GETs to smoke");

      const lines = [
        "#!/usr/bin/env bash",
        "# Smoke checks for the API the legacy app calls, generated by portamp.",
        "#",
        "# portamp wrote this and did not run it. Running it makes live calls to",
        "# whatever BASE_URL names; do that only against a server you are",
        "# authorized to test. GETs only; anything that writes was left out" + (skipped ? ` (${skipped} call(s))` : "") + ".",
        "# Auth is yours to add: an -H per line, from a credential this file",
        "# deliberately does not contain.",
        "set -euo pipefail",
        "",
        ': "${BASE_URL:?set BASE_URL to the server under test}"',
        "",
        "fail=0",
        ...gets.map((path) => [
          `printf '%s ' "GET ${path}"`,
          `code=$(curl -s -o /dev/null -w '%{http_code}' "\${BASE_URL}${path}") || code=000`,
          `printf '%s\\n' "$code"`,
          `case "$code" in 2*|3*) ;; *) fail=1 ;; esac`,
        ].join("\n")),
        "",
        "exit $fail",
        "",
      ];
      await ctx.write("smoke.sh", lines.join("\n"));
      log.info(`${gets.length} GET(s) in smoke.sh, ${skipped} write(s) excluded`);
    });
  },
};
