/**
 * Mock handlers for the endpoints the port calls.
 *
 * A ported front end cannot be developed against nothing, and pointing it at
 * the real system to get a page to render is how a migration ends up making
 * writes nobody authorized. This gives the port something to talk to.
 *
 * No captured value survives into this file. A recorded body contributes its
 * property names and their types and nothing else; every value is a placeholder
 * derived from the type. Recorded traffic is somebody's real data, and a mock
 * that carries it is a copy of that data in a repository.
 *
 *   msw: true
 */

const templated = (path) =>
  String(path)
    .replace(/\$\{\s*([\w$.]+)\s*\}/g, (_, n) => `:${n.split(".").pop()}`)
    .replace(/\{([\w$]+)\}/g, ":$1")
    .split("?")[0];

/** A placeholder that shows the type without reproducing anybody's data. */
const placeholder = (type, name) => {
  if (type === "number") return "0";
  if (type === "boolean") return "false";
  if (type === "object") return "{}";
  return JSON.stringify(`<${name}>`);
};

const collectionOf = (path) => {
  const segments = templated(path).split("/").filter((s) => s && !s.startsWith(":"));
  return segments.at(-1) ?? "items";
};

function bodyFor(endpoint, method, path) {
  const shape = endpoint?.observedBody;
  if (shape && shape !== "not json" && typeof shape === "object") {
    const props = Object.entries(shape).map(([k, t]) => `      ${JSON.stringify(k)}: ${placeholder(t, k)},`);
    return `{\n${props.join("\n")}\n    }`;
  }
  // Nothing was observed, so the mock says so in the payload rather than
  // inventing rows that a developer might mistake for the real shape.
  const note = JSON.stringify(`portamp did not observe this response. Replace this with the real shape.`);
  if (method === "GET" && !templated(path).split("/").at(-1)?.startsWith(":")) {
    return `{\n      ${JSON.stringify(collectionOf(path))}: [],\n      "_portamp": ${note},\n    }`;
  }
  return `{\n      "_portamp": ${note},\n    }`;
}

export function buildHandlers(ctx) {
  const observed = new Map((ctx.model?.endpoints ?? []).map((e) => [`${e.method} ${templated(e.path)}`, e]));
  const seen = new Set();
  const handlers = [];
  const unverified = [];

  const all = [
    ...(ctx.api?.calls ?? []).map((c) => ({ method: c.method, path: c.path })),
    ...(ctx.model?.endpoints ?? []).map((e) => ({ method: e.method, path: e.path })),
  ];

  for (const call of all) {
    const path = templated(call.path);
    const key = `${call.method} ${path}`;
    if (seen.has(key)) continue;
    seen.add(key);

    const endpoint = observed.get(key);
    const status = endpoint?.statuses?.find((s) => s >= 200 && s < 300) ?? 200;
    if (!endpoint?.observedBody || endpoint.observedBody === "not json") {
      unverified.push(`The mock for ${key} returns a placeholder. No real response was ever observed.`);
    }
    handlers.push({ method: call.method, path, status, body: bodyFor(endpoint, call.method, call.path), observed: Boolean(endpoint) });
  }

  handlers.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));
  return { handlers, unverified };
}

export function renderHandlers(handlers) {
  const body = handlers.map((h) => `  // ${h.observed ? "Seen against the running system." : "Read from the source; never exercised."}
  http.${h.method.toLowerCase()}(${JSON.stringify(h.path)}, () =>
    HttpResponse.json(${h.body}, { status: ${h.status} })
  ),`).join("\n\n");

  return `import { http, HttpResponse } from "msw";

/**
 * Generated by portamp. Every value below is a placeholder: property names and
 * types come from observed traffic, values never do.
 *
 * Fill these in as you learn the real shapes. A handler that still returns
 * "_portamp" has not been checked against anything.
 */
export const handlers = [
${body}
];
`;
}

/**
 * The states nobody exercises are the states nobody built. These wrap the
 * same endpoints in the three conditions a front end meets in the field and a
 * developer machine never shows: a slow answer, a failing one, and an empty
 * one. Use them one at a time; a suite that runs against all three has
 * exercised every state the emitted components render.
 */
export function renderScenarios(handlers, complaints = []) {
  const routes = handlers.map((h) => `  ["${h.method.toLowerCase()}", ${JSON.stringify(h.path)}],`).join("\n");
  return `import { http, HttpResponse, delay } from "msw";
import { handlers } from "./handlers.js";

const ROUTES = [
${routes}
];

/** Every endpoint, three seconds late. Loading states live or die here. */
export const slow = (ms = 3000) =>
  ROUTES.map(([method, path]) =>
    http[method](path, async (info) => {
      await delay(ms);
      for (const handler of handlers) {
        const result = await handler.run(info);
        if (result?.response) return result.response;
      }
      return HttpResponse.json({}, { status: 200 });
    })
  );

/** Every endpoint refusing. The error states, and the retry buttons. */
export const failing = (status = 500) =>
  ROUTES.map(([method, path]) => http[method](path, () => HttpResponse.json(
    { error: "scenario", description: "the failing() scenario is on" }, { status }
  )));

/** Every collection empty. The most commonly missing state there is. */
export const empty = () =>
  ROUTES.map(([method, path]) => http[method](path, () => HttpResponse.json(
    method === "get" ? [] : {}, { status: 200 }
  )));

/**
 * Every write refused as a validation failure${complaints.length ? ", in the messages the\n * original app was actually seen making" : ""}. The form's error rendering,
 * exercised without a server.
 */
export const rejecting = (status = 422) =>
  ROUTES.filter(([method]) => method !== "get").map(([method, path]) =>
    http[method](path, () => HttpResponse.json(
      { errors: ${JSON.stringify(complaints.length ? complaints.slice(0, 10) : ["The input was not accepted."])} }, { status }
    )));
`;
}

const BROWSER = `import { setupWorker } from "msw/browser";
import { handlers } from "./handlers.js";

// Start this only in development. A service worker that intercepts requests in
// production is an outage with an unusual cause.
export const worker = setupWorker(...handlers);
`;

const NODE = `import { setupServer } from "msw/node";
import { handlers } from "./handlers.js";

export const server = setupServer(...handlers);
`;

export default {
  name: "output-msw",
  version: "0.1.0",
  class: "output",
  setup({ on, log }) {
    on("emit", async (ctx) => {
      if (!ctx.config.msw) return log.debug("not requested");

      const { handlers, unverified } = buildHandlers(ctx);
      if (!handlers.length) return log.info("no endpoints to mock");

      await ctx.write("src/mocks/handlers.js", renderHandlers(handlers));
      const complaints = [...new Set(
        (ctx.forms ?? []).flatMap((form) => form.fields.map((field) =>
          typeof field.observed === "string" ? field.observed : field.observed?.message
        )).filter((m) => typeof m === "string" && m.trim())
      )];
      await ctx.write("src/mocks/scenarios.js", renderScenarios(handlers, complaints));
      await ctx.write("src/mocks/browser.js", BROWSER);
      await ctx.write("src/mocks/server.js", NODE);
      for (const note of unverified) ctx.unverified(note);
      log.info(`${handlers.length} handler(s), ${handlers.filter((h) => h.observed).length} from observed traffic`);
    });
  },
};
