import { jsString } from "../dsp-ir/emit.js";

const pascal = (sel) =>
  String(sel).split(/[-_\s]/).filter(Boolean).map((p) => p[0].toUpperCase() + p.slice(1)).join("");

/**
 * A story per emitted component, one per state the component can actually
 * reach. The states are the point: the emitted component renders loading,
 * error and empty on purpose, and a story for each is how anybody sees them
 * without contriving the data by hand.
 *
 * Off unless asked for, because not every project has Storybook.
 *   storybook: true
 */
export default {
  name: "output-storybook",
  version: "0.1.0",
  class: "output",
  setup({ on, log }) {
    on("emit", async (ctx) => {
      if (!ctx.config.storybook) return log.debug("not requested");

      let written = 0;
      for (const screen of ctx.screens) {
        const name = pascal(screen.selector) || "Screen";
        const collection = screen.observed?.collection;
        const columns = collection?.columns ?? [];
        // A row shaped like the columns the original showed, so the default
        // story is not an empty table pretending to be a full one.
        const row = columns.length
          ? "{ " + columns.map((c, i) => `${jsString(camel(c))}: ${jsString("Example " + (i + 1))}`).join(", ") + " }"
          : '{ id: "1", name: "Example" }';

        await ctx.write(`src/features/${name}/${name}.stories.jsx`, STORY({ name, row, screen }));
        written += 1;

        // The other targets get the same four states. A story file follows its
        // component: whichever emitters ran, their output is what gets stories.
        if (ctx.config.vue) {
          await ctx.write(`src/features/${name}/${name}.vue.stories.js`, CSF({ name, row, importPath: `./${name}.vue`, framework: "vue" }));
          written += 1;
        }
        if (ctx.config.svelte) {
          await ctx.write(`src/features/${name}/${name}.svelte.stories.js`, CSF({ name, row, importPath: `./${name}.svelte`, framework: "svelte" }));
          written += 1;
        }
        if (ctx.config.lit || ctx.config.html) {
          const importPath = ctx.config.lit ? `../../elements/${name}.lit.js` : `../../elements/${name}.js`;
          await ctx.write(`src/features/${name}/${name}.element.stories.js`, WEB_STORY({ name, row, importPath, tag: screen.selector.includes("-") ? screen.selector : `x-${screen.selector}` }));
          written += 1;
        }
      }
      log.info(`${written} story file(s), four states each`);
      if (written) {
        ctx.note("Storybook stories were emitted with example data, not with anything from the legacy system.");
      }
    });
  },
};

const camel = (text) => {
  const cleaned = String(text).replace(/[^A-Za-z0-9]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ""));
  return cleaned.charAt(0).toLowerCase() + cleaned.slice(1);
};

const STORY = ({ name, row, screen }) => `import ${name} from "./${name}.jsx";

/**
 * Generated by portamp from ${screen.file}.
 *
 * One story per state the component can reach. The data below is invented for
 * the story and came from nowhere near the legacy system.
 */
export default {
  title: "Ported/${name}",
  component: ${name},
};

const rows = [${row}, ${row}];

export const Body = { args: { loading: false, error: null, data: rows${extra(screen)} } };

export const Loading = { args: { loading: true, error: null, data: [] } };

export const Failed = { args: { loading: false, error: new Error("The service is unavailable"), data: [] } };

/** The state a port forgets. If this renders nothing, the port has the defect. */
export const Empty = { args: { loading: false, error: null, data: []${extra(screen)} } };

// The assertion, not just the exhibit: the test runner fails this story the
// moment the empty state stops rendering anything a person can read.
Empty.play = async ({ canvasElement }) => {
  if (!canvasElement.textContent.trim()) {
    throw new Error("The empty state renders nothing. That is the most common port defect, and this story exists to catch it.");
  }
};
`;

function extra(screen) {
  const fields = screen.observed?.fields ?? [];
  const inputs = screen.inputs ?? [];
  const names = [...new Set([...fields.map((f) => f.name), ...inputs])].filter(Boolean);
  return names.length ? ", " + names.map((n) => `${n}: ${jsString("example")}`).join(", ") : "";
}

/**
 * CSF3 works for Vue and Svelte alike: the component is the default export's
 * subject and the states are args. The renderer add-on does the rest, which
 * is the point of the format.
 */
const CSF = ({ name, row, importPath, framework }) => `import ${name} from "${importPath}";

/**
 * Generated by portamp for the ${framework} target. Example data only;
 * nothing here came from the legacy system.
 */
export default {
  title: "Ported/${name}",
  component: ${name},
};

export const Body = { args: { loading: false, error: null, data: [${row}, ${row}] } };
export const Loading = { args: { loading: true } };
export const Failed = { args: { loading: false, error: { message: "The service said no." } } };
export const Empty = { args: { loading: false, error: null, data: [] } };

Empty.play = async ({ canvasElement }) => {
  if (!canvasElement.textContent.trim()) {
    throw new Error("The empty state renders nothing. That is the most common port defect, and this story exists to catch it.");
  }
};
`;

const WEB_STORY =({ name, row, importPath, tag }) => `import "${importPath}";

/**
 * Generated by portamp for the custom element target. The element takes rich
 * values as properties, so the render function sets them instead of writing
 * attributes.
 */
const render = (args) => {
  const el = document.createElement("${tag}");
  Object.assign(el, args);
  if (typeof el.set === "function") el.set(args);
  return el;
};

export default { title: "Ported/${name} (element)", render };

export const Body = { args: { loading: false, error: null, data: [${row}, ${row}] } };
export const Loading = { args: { loading: true } };
export const Failed = { args: { loading: false, error: { message: "The service said no." } } };
export const Empty = { args: { loading: false, error: null, data: [] } };

Empty.play = async ({ canvasElement }) => {
  if (!canvasElement.textContent.trim()) {
    throw new Error("The empty state renders nothing. That is the most common port defect, and this story exists to catch it.");
  }
};
`;
