const pascal = (sel) =>
  String(sel).split(/[-_\s]/).filter(Boolean).map((p) => p[0].toUpperCase() + p.slice(1)).join("");

/**
 * A story per emitted component, one per state the component can actually
 * reach. The states are the point: the emitted component renders loading,
 * error and empty on purpose, and a story for each is how anybody sees them
 * without contriving the data by hand.
 *
 * Off unless asked for, because not every project has Storybook.
 *   storybook: true
 */
export default {
  name: "output-storybook",
  version: "0.1.0",
  class: "output",
  setup({ on, log }) {
    on("emit", async (ctx) => {
      if (!ctx.config.storybook) return log.debug("not requested");

      let written = 0;
      for (const screen of ctx.screens) {
        const name = pascal(screen.selector) || "Screen";
        const collection = screen.observed?.collection;
        const columns = collection?.columns ?? [];
        // A row shaped like the columns the original showed, so the default
        // story is not an empty table pretending to be a full one.
        const row = columns.length
          ? "{ " + columns.map((c, i) => `${JSON.stringify(camel(c))}: ${JSON.stringify("Example " + (i + 1))}`).join(", ") + " }"
          : '{ id: "1", name: "Example" }';

        await ctx.write(`src/features/${name}/${name}.stories.jsx`, STORY({ name, row, screen }));
        written += 1;
      }
      log.info(`${written} story file(s), four states each`);
      if (written) {
        ctx.note("Storybook stories were emitted with example data, not with anything from the legacy system.");
      }
    });
  },
};

const camel = (text) => {
  const cleaned = String(text).replace(/[^A-Za-z0-9]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ""));
  return cleaned.charAt(0).toLowerCase() + cleaned.slice(1);
};

const STORY = ({ name, row, screen }) => `import ${name} from "./${name}.jsx";

/**
 * Generated by portamp from ${screen.file}.
 *
 * One story per state the component can reach. The data below is invented for
 * the story and came from nowhere near the legacy system.
 */
export default {
  title: "Ported/${name}",
  component: ${name},
};

const rows = [${row}, ${row}];

export const Body = { args: { loading: false, error: null, data: rows${extra(screen)} } };

export const Loading = { args: { loading: true, error: null, data: [] } };

export const Failed = { args: { loading: false, error: new Error("The service is unavailable"), data: [] } };

/** The state a port forgets. If this renders nothing, the port has the defect. */
export const Empty = { args: { loading: false, error: null, data: []${extra(screen)} } };
`;

function extra(screen) {
  const fields = screen.observed?.fields ?? [];
  const inputs = screen.inputs ?? [];
  const names = [...new Set([...fields.map((f) => f.name), ...inputs])].filter(Boolean);
  return names.length ? ", " + names.map((n) => `${n}: ${JSON.stringify("example")}`).join(", ") : "";
}
