import { inferBackendEntities } from "./entities.js";

/**
 * The other half of full stack: a real server, not a fixture that echoes the
 * same canned response forever. Reads the same `ctx.api.calls` every other
 * emitter already reads, wires only the routes the legacy app actually
 * called to a store class it writes verbatim, and seeds each entity from
 * whatever shape was actually observed (dsp-entities, a recorded response, a
 * declared spec) rather than a value nobody proved. A call this reader
 * cannot pair into a collection and an item is named in BACKEND.md and left
 * to the fixture-or-501 path serve.js already has, never forced into a CRUD
 * shape it does not have. Requires `--site true`: the server this writes
 * into is output-site's own serve.js, not a standalone one.
 */

const STORE_JS = `/**
 * The port's own embedded datastore: one JSON file per entity, no dependency
 * and no external database. A write goes to a temp file and is renamed into
 * place, so a crash mid write leaves the previous, still valid file rather
 * than a half written one. The first read of an entity that has never been
 * written seeds it from the shape backend.js inferred, so a fresh checkout
 * has something to list before the first write ever happens; every write
 * after that persists across requests and across restarts of the process.
 */

import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

export class Store {
  constructor(dir, seeds = {}) {
    this.dir = dir;
    this.seeds = seeds;
    this.cache = new Map();
  }

  async #load(name) {
    if (this.cache.has(name)) return this.cache.get(name);
    const file = join(this.dir, \`\${name}.json\`);
    const rows = await readFile(file, "utf8").then(JSON.parse).catch(() => null);
    if (rows === null) {
      const seeded = this.seeds[name] ?? [];
      this.cache.set(name, seeded);
      await this.#save(name, seeded);
      return seeded;
    }
    this.cache.set(name, rows);
    return rows;
  }

  async #save(name, rows) {
    this.cache.set(name, rows);
    const file = join(this.dir, \`\${name}.json\`);
    await mkdir(dirname(file), { recursive: true });
    const tmp = \`\${file}.\${process.pid}.\${Date.now()}.tmp\`;
    await writeFile(tmp, JSON.stringify(rows, null, 2) + "\\n", "utf8");
    await rename(tmp, file);
  }

  async list(name) {
    return this.#load(name);
  }

  async get(name, id) {
    return (await this.#load(name)).find((r) => String(r.id) === String(id)) ?? null;
  }

  async create(name, row) {
    const rows = await this.#load(name);
    const numeric = rows.map((r) => Number(r.id)).filter((n) => Number.isFinite(n));
    const id = row?.id ?? (numeric.length ? Math.max(...numeric) + 1 : 1);
    const record = { ...row, id };
    rows.push(record);
    await this.#save(name, rows);
    return record;
  }

  async update(name, id, patch) {
    const rows = await this.#load(name);
    const i = rows.findIndex((r) => String(r.id) === String(id));
    if (i === -1) return null;
    rows[i] = { ...rows[i], ...patch, id: rows[i].id };
    await this.#save(name, rows);
    return rows[i];
  }

  async remove(name, id) {
    const rows = await this.#load(name);
    const i = rows.findIndex((r) => String(r.id) === String(id));
    if (i === -1) return false;
    rows.splice(i, 1);
    await this.#save(name, rows);
    return true;
  }
}
`;

const BACKEND_JS = (entities) => `/**
 * Real routes, wired to the store, for exactly the calls the legacy app
 * actually made. Generated by output-backend; ${entities.length} entit${entities.length === 1 ? "y" : "ies"} wired.
 * See ../BACKEND.md for what was inferred, from where, and what was left out.
 */

import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { matchPath } from "../src/app/match.js";
import { Store } from "./store.js";

const store = new Store(join(dirname(fileURLToPath(import.meta.url)), "data"), ${JSON.stringify(
  Object.fromEntries(entities.map((e) => [e.name, [e.seed]])),
  null,
  2
).replace(/\n/g, "\n  ")});

const ROUTES = ${JSON.stringify(
  entities.flatMap((e) => e.verbs.map((v) => ({ method: v.method, path: v.path, op: v.op, entity: e.name }))),
  null,
  2
).replace(/\n/g, "\n  ")};

async function readJson(req) {
  const chunks = [];
  for await (const chunk of req) chunks.push(chunk);
  const raw = Buffer.concat(chunks).toString("utf8");
  if (!raw) return {};
  try {
    return JSON.parse(raw);
  } catch {
    return {};
  }
}

function send(res, status, body) {
  res.writeHead(status, {
    "content-type": "application/json",
    "x-portamp-backend": "generated crud over an embedded store, no external database",
  });
  res.end(body === undefined ? "" : JSON.stringify(body));
}

/** Tries the generated backend first; \`false\` means this request is not one of its routes and serve.js's own fixture-or-501 path should answer it instead. */
export async function handleBackend(req, res, method, path) {
  const route = ROUTES.find((r) => r.method === method && matchPath(r.path, path));
  if (!route) return false;
  const { params } = matchPath(route.path, path);

  if (route.op === "list") { send(res, 200, await store.list(route.entity)); return true; }
  if (route.op === "get") {
    const row = await store.get(route.entity, params.id);
    send(res, row ? 200 : 404, row ?? { error: "not found", id: params.id });
    return true;
  }
  if (route.op === "create") { send(res, 201, await store.create(route.entity, await readJson(req))); return true; }
  if (route.op === "update") {
    const row = await store.update(route.entity, params.id, await readJson(req));
    send(res, row ? 200 : 404, row ?? { error: "not found", id: params.id });
    return true;
  }
  if (route.op === "remove") {
    const ok = await store.remove(route.entity, params.id);
    send(res, ok ? 204 : 404, ok ? undefined : { error: "not found", id: params.id });
    return true;
  }
  return false;
}
`;

function backendReport(entities, skipped) {
  const lines = [
    "# The generated backend", "",
    "Real routes over a real, persisted store, wired only for the calls the",
    "legacy app actually made. Nothing here is a fixture: a create really",
    "creates a row, and the next list call sees it.", "",
  ];
  if (entities.length) {
    lines.push("## Wired", "");
    for (const e of entities) {
      lines.push(`### ${e.name}`, "");
      lines.push("| method | path | operation |", "| --- | --- | --- |");
      for (const v of e.verbs) lines.push(`| ${v.method} | \`${v.path}\` | ${v.op} |`);
      lines.push("");
      lines.push(
        e.shapeSource
          ? `Seeded from ${e.shapeSource}: \`${JSON.stringify(e.seed)}\`.`
          : `No shape was ever observed for this entity; seeded with an id only: \`${JSON.stringify(e.seed)}\`. A create call carries whatever fields the client actually sends, so this is a starting point, not a schema.`
      );
      lines.push("");
    }
  } else {
    lines.push("Nothing was wired. See below for why.", "");
  }
  if (skipped.length) {
    lines.push("## Left to the existing fixture or 501 path", "", "| method | path | why |", "| --- | --- | --- |");
    for (const s of skipped) lines.push(`| ${s.method} | \`${s.path}\` | ${s.reason} |`);
    lines.push("");
  }
  lines.push(
    "---", "",
    "An entity here is a reading of the calls the app makes, not a schema",
    "somebody wrote down. A property no create call ever sends is not proven",
    "absent, and a real service's own model outranks this the moment somebody",
    "who owns it writes it down."
  );
  return lines.join("\n") + "\n";
}

export default {
  name: "output-backend",
  version: "0.1.0",
  class: "output",
  setup({ on, log }) {
    on("emit", async (ctx) => {
      if (!ctx.config.backend) return log.debug("not requested");
      if (!ctx.site) {
        ctx.unverified("--backend true needs --site true: the server it wires into is output-site's own serve.js.");
        return;
      }
      if (!ctx.api?.calls?.length) {
        ctx.unverified("--backend true was asked for, but no API calls were read from the source to infer a backend from.");
        return;
      }

      const { entities, skipped } = inferBackendEntities(ctx);
      if (!entities.length) {
        await ctx.write("BACKEND.md", backendReport(entities, skipped));
        ctx.unverified(`--backend true found no call it could pair into a collection and an item to wire; ${skipped.length} call(s) named in BACKEND.md.`);
        return;
      }

      await ctx.write("server/store.js", STORE_JS);
      await ctx.write("server/backend.js", BACKEND_JS(entities));
      await ctx.write("BACKEND.md", backendReport(entities, skipped));
      await ctx.write(
        "portamp.backend.json",
        JSON.stringify(
          {
            entities: entities.map((e) => ({ name: e.name, verbs: e.verbs, properties: e.properties, shapeSource: e.shapeSource })),
            skipped,
          },
          null,
          2
        ) + "\n"
      );

      const blind = entities.filter((e) => !e.shapeSource).length;
      log.info(`${entities.length} entit(ies) wired to a real store, ${skipped.length} call(s) left to the existing fixture or 501 path`);
      if (blind) ctx.unverified(`${blind} wired entit(ies) had no observed shape and were seeded with an id only.`);
    });
  },
};
