/**
 * The modernization plan as architecture decision records.
 *
 * A plan in one file gets read once and skimmed after. A decision record per
 * decision gives each one a life of its own: a status a team can flip, a
 * context that is the measured legacy fact, and a place for the consequences
 * to be argued about. Every record starts as `proposed`, because portamp does
 * not accept its own proposals.
 *
 *   adr: true
 */
const slug = (text) =>
  String(text).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").split("-").slice(0, 6).join("-");

export function renderRecord(decision, index, archetype) {
  return `# ${index}. ${decision.title}

Status: proposed
Date: generated by portamp
${decision.severity ? `Severity of the underlying observation: ${decision.severity}\n` : ""}
## Context

${decision.because}

This follows from reading the legacy app as **${archetype}** (see
ARCHITECTURE.md for the evidence). If that reading is wrong, this record's
premise goes with it, and the record should be rejected on those grounds
rather than reworded.

## Decision

${decision.instead}

## Consequences

Adopting this changes how the rebuilt app behaves, not only how it is built,
so it needs an owner who can say yes. portamp proposed it (from: ${decision.source})
and has deliberately not implemented it.
`;
}

export default {
  name: "output-adr",
  version: "0.1.0",
  class: "output",
  setup({ on, log }) {
    on("emit", async (ctx) => {
      if (!ctx.config.adr) return log.debug("not requested");
      if (!ctx.modernization?.decisions?.length) return log.info("no decisions to record");

      let n = 0;

      // A contested archetype reading is itself a decision somebody must
      // make, and every other record leans on it, so it goes first as its
      // own ADR instead of a line inside a report nobody reopens.
      if (ctx.archetype?.contested && ctx.archetype.ranked?.length >= 2) {
        n += 1;
        const [first, second] = ctx.archetype.ranked;
        const pct = (v) => `${Math.round(v * 100)}%`;
        await ctx.write(`docs/adr/${String(n).padStart(4, "0")}-what-kind-of-app-this-is.md`, `# ${n}. What kind of app this is

Status: proposed
Date: generated by portamp

## Context

The run read this app as **${first.id}** at ${pct(first.confidence)} confidence, and
**${second.id}** scored ${pct(second.confidence)} — within the margin where portamp
reports a contest instead of a verdict. ARCHITECTURE.md carries the signals
each reading matched and missed.

## Decision

Undecided on purpose. Every following record assumes the **${first.id}** reading;
whoever knows the product should confirm or overturn it here, because
overturning it later reprices every record after this one.

## Consequences

Until this flips to accepted, the records that follow are conditional, and
the honest reading of the plan is "if this is a ${first.id}".
`);
      }

      for (const decision of ctx.modernization.decisions) {
        n += 1;
        await ctx.write(
          `docs/adr/${String(n).padStart(4, "0")}-${slug(decision.title)}.md`,
          renderRecord(decision, n, ctx.archetype?.best?.id ?? "unknown")
        );
      }
      log.info(`${n} decision record(s), every one proposed`);
    });
  },
};
