/**
 * The modernization plan as architecture decision records.
 *
 * A plan in one file gets read once and skimmed after. A decision record per
 * decision gives each one a life of its own: a status a team can flip, a
 * context that is the measured legacy fact, and a place for the consequences
 * to be argued about. Every record starts as `proposed`, because portamp does
 * not accept its own proposals.
 *
 *   adr: true
 */
const slug = (text) =>
  String(text).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").split("-").slice(0, 6).join("-");

export function renderRecord(decision, index, archetype) {
  return `# ${index}. ${decision.title}

Status: proposed
Date: generated by portamp
${decision.severity ? `Severity of the underlying observation: ${decision.severity}\n` : ""}
## Context

${decision.because}

This follows from reading the legacy app as **${archetype}** (see
ARCHITECTURE.md for the evidence). If that reading is wrong, this record's
premise goes with it, and the record should be rejected on those grounds
rather than reworded.

## Decision

${decision.instead}

## Consequences

Adopting this changes how the rebuilt app behaves, not only how it is built,
so it needs an owner who can say yes. portamp proposed it (from: ${decision.source})
and has deliberately not implemented it.
`;
}

export default {
  name: "output-adr",
  version: "0.1.0",
  class: "output",
  setup({ on, log }) {
    on("emit", async (ctx) => {
      if (!ctx.config.adr) return log.debug("not requested");
      if (!ctx.modernization?.decisions?.length) return log.info("no decisions to record");

      let n = 0;
      for (const decision of ctx.modernization.decisions) {
        n += 1;
        await ctx.write(
          `docs/adr/${String(n).padStart(4, "0")}-${slug(decision.title)}.md`,
          renderRecord(decision, n, ctx.archetype?.best?.id ?? "unknown")
        );
      }
      log.info(`${n} decision record(s), every one proposed`);
    });
  },
};
